const baseUrl = "http://localhost/Backend/";

const EndPoint = {
    login: `${baseUrl}api/User/Login`,
    getStudentInfo: `${baseUrl}api/Student/getStudentInfo`,
    checkApplicationStatus: `${baseUrl}api/Student/getStudentApplicationStatus`,
    sendApplication: `${baseUrl}api/Student/sendApplication`,
    imageUrl: `${baseUrl}Content/profileImages/`,
    getAdminInfo: `${baseUrl}api/Admin/getAdminInfo`,
    getAllStudents: `${baseUrl}api/Admin/getAllStudent`,
    updatePassword: `${baseUrl}api/Admin/UpdatePassword`,
    getAllBudget: `${baseUrl}api/Admin/getAllBudget`,
    addFacultyMember: `${baseUrl}api/Admin/AddFacultyMember`,
    getFacultyMembers: `${baseUrl}api/Admin/FacultyMembers`,
    getCommitteeMembers: `${baseUrl}api/Admin/CommitteeMembers`,
    addCommitteeMember: `${baseUrl}api/Admin/AddCommitteeMember`,
    getApplication: `${baseUrl}api/Committee/GetApplication`,
    updateProfileImage: `${baseUrl}api/Student/UpdateProfileImage`,
    committeeMemberInfo: `${baseUrl}api/Committee/CommitteeMembers`,
    houseAgreement: `${baseUrl}Content/HouseAgreement/`,
    salarySlip: `${baseUrl}Content/SalarySlip/`,
    deathCertificate: `${baseUrl}Content/DeathCertificates/`,
    giveSuggestion: `${baseUrl}api/Committee/GiveSuggestion`,
    getBalance: `${baseUrl}api/Committee/GetBalance`,
    switchRole: `${baseUrl}api/User/SwitchRole`,
    facultyInfo: `${baseUrl}api/Faculty/FacultyInfo`,
    adminApplication: `${baseUrl}api/Admin/ApplicationSuggestions`,
    acceptApplication: `${baseUrl}api/Admin/AcceptApplication`,
    rejectApplication: `${baseUrl}api/Admin/RejectApplication`,
    accepted: `${baseUrl}api/Admin/AcceptedApplication`,
    rejected: `${baseUrl}api/Admin/RejectedApplication`,
    assignGrader: `${baseUrl}api/Admin/AssignGrader`,
    meritBaseShortListing: `${baseUrl}api/Admin/MeritBaseShortListing`,
    addStudent: `${baseUrl}api/Admin/AddStudent`,
    addPolicies: `${baseUrl}api/Admin/AddPolicies`,
    getPolicies: `${baseUrl}api/Admin/getPolicies`,
    unAssignedStudents: `${baseUrl}api/Admin/unAssignedGraders`,
    addBudget: `${baseUrl}api/Admin/AddBudget`,
    getGraderInfo: `${baseUrl}api/Admin/gradersInformation`,
    rateGraderPerformance: `${baseUrl}api/Faculty/RateGraderPerformance`,
    getMeritBaseShortListedStudent: `${baseUrl}api/Admin/GetMeritBaseShortListedStudent`
};

export default EndPoint;
